# ===========================
# [ADDED] Observability: minimal logger + trace file writer
# ===========================
import json  # [ADDED]
import os

import notifier
import requests
import logging  # [ADDED]
import sys  # [ADDED]
import uuid  # [ADDED]
import smtplib
import ssl
from datetime import datetime  # [ADDED]
from data_manager import DataManager
from notification_manager import NotificationManager
from flight_search import FlightSearch
from dotenv import load_dotenv
from typing import Optional, Tuple

#verbose=True in load_dotenv() makes python-dotenv print debug info about which .env file it tries to load and whether it succeeds. It’s safe and only affects logging.
load_dotenv(verbose=True)

MyEmailSender = os.getenv("SEND_EMAIL")
app_password = os.getenv("APP_PW_GMAIL")
MyEmailReciever = os.environ.get("RECIEVE_EMAIL")

def _setup_logger(level=logging.INFO):  # [ADDED]
    logger = logging.getLogger("travel")
    logger.handlers.clear()
    logger.setLevel(level)
    ch = logging.StreamHandler(sys.stdout)
    ch.setLevel(level)
    ch.setFormatter(logging.Formatter("%(levelname)s %(message)s"))
    logger.addHandler(ch)
    return logger

def _write_trace_file(trace_obj, path="trace.json"):  # [ADDED]
    with open(path, "w", encoding="utf-8") as f:
        json.dump(trace_obj, f, indent=2, sort_keys=True, ensure_ascii=False)

# [ADDED] Quick SMTP diagnostics to see which path works on this network
def _smtp_probe(host="smtp.gmail.com", timeout=8):
    results = {}
    # STARTTLS on 587
    try:
        with smtplib.SMTP(host, 587, timeout=timeout) as s:
            s.ehlo()
            s.starttls(context=ssl.create_default_context())
            s.ehlo()
            results["587_STARTTLS"] = "OK"
    except Exception as e:
        results["587_STARTTLS"] = f"FAIL: {e!r}"
    # Implicit SSL on 465
    try:
        with smtplib.SMTP_SSL(host, 465, timeout=timeout, context=ssl.create_default_context()) as s:
            s.ehlo()
            results["465_SSL"] = "OK"
    except Exception as e:
        results["465_SSL"] = f"FAIL: {e!r}"
    return results

logger = _setup_logger()  # [ADDED] INFO-level concise logs
run_trace = {  # [ADDED] per-run trace scaffold
    "run_id": str(uuid.uuid4()),
    "started_utc": datetime.utcnow().isoformat() + "Z",
    "env_presence": {
        "AMADEUS_API_KEY_present": bool(os.getenv("AMADEUS_API_KEY")),
        "AMADEUS_API_SECRET_present": bool(os.getenv("AMADEUS_API_SECRET")),
        "AMADEUS_AUTH_TOKEN_ENDPOINT_present": bool(os.getenv("AMADEUS_AUTH_TOKEN_ENDPOINT")),
        "AMADEUS_API_BASE_present": bool(os.getenv("AMADEUS_API_BASE")),
    },
    "destinations": []
}

# [ADDED] log SMTP probe results up-front
probe = _smtp_probe()
logger.info("SMTP probe: %s", probe)
run_trace["smtp_probe"] = probe


def evaluate_price_drop(
    sheet_row: dict,
    cheapest_offer: Optional[dict],
) -> Tuple[bool, dict]:
    """
    Returns (should_notify, payload).
    payload has: subject, body_text, body_html.
    """
    city = (sheet_row.get("city") or "").strip()
    # Your sheet may use 'lowestPrice' (100 Days of Code project) – keep both just in case
    sheet_price_str = (sheet_row.get("lowestPrice") or sheet_row.get("lowest_price") or "").strip()
    try:
        sheet_price = float(sheet_price_str) if sheet_price_str else None
    except ValueError:
        sheet_price = None

    if not cheapest_offer:
        return (False, {})

    price = (cheapest_offer.get("price") or {}).get("total")
    currency = (cheapest_offer.get("price") or {}).get("currency") or "USD"
    try:
        current = float(price) if price is not None else None
    except ValueError:
        current = None

    if current is None or sheet_price is None:
        return (False, {})

    # Only alert when the new price is strictly lower
    if current >= sheet_price:
        return (False, {})

    drop_abs = sheet_price - current
    subject = f"Lower price found: {city} now {currency} {current:.2f} (was {sheet_price:.2f})"

    body_text = (
        f"Good news!\n\n"
        f"Destination: {city}\n"
        f"Lower price found: {currency} {current:.2f}\n"
        f"Your baseline price: {currency} {sheet_price:.2f}\n"
        f"Difference: {currency} {drop_abs:.2f}\n\n"
        f"This email was auto-generated by Flight Deals."
    )

    payload = {
        "subject": subject,
        "body_text": body_text,
    }
    return (True, payload)

flight_search = FlightSearch()
data_manager = DataManager()
data_manager._debug_headers()
sheet_data = data_manager.get_destination_data()


# Run the fill if any row is missing iataCode
if any(not (row.get("iataCode") or "").strip() for row in sheet_data):
    #Test if it's loading.
    print("AMADEUS_API_KEY present? ->", bool(os.getenv("AMADEUS_API_KEY")))
    print("AMADEUS_API_SECRET present? ->", bool(os.getenv("AMADEUS_API_SECRET")))
    print("AMADEUS_AUTH_TOKEN_ENDPOINT present? ->", bool(os.getenv("AMADEUS_AUTH_TOKEN_ENDPOINT")))
    print("AMADEUS_API_BASE present? ->", bool(os.getenv("AMADEUS_API_BASE")))
    print("Tokyo ->", flight_search.get_destination_code("Tokyo"))  # expect TYO

    for row in sheet_data:
        if not (row.get("iataCode") or "").strip():
            row["iataCode"] = flight_search.get_destination_code(row["city"]) or row.get("iataCode") or ""

    unresolved = [row["city"] for row in sheet_data if not (row.get("iataCode") or "").strip()]
    if unresolved:
        print("Unresolved cities (no IATA):", unresolved)

    print(f"sheet_data test chapman:\n {sheet_data}")
    print(f"IATA Code {row.get('iataCode')}")
    #Set the dictionary in other class with self to the sheet data
    data_manager.destination_data = sheet_data
    data_manager.update_destination_codes()

#New section for query flight offers origin to each destination then pick the cheapest.
try:
    # 1) pick your origin, by the code. Could request user input instead
    ORIGIN = "CHI"
    run_trace["origin"] = ORIGIN  # [ADDED] include in trace

    # 2) Build destination list from sheet
    dest_codes = []
    for r in sheet_data: #<- r is arrbitrary loop variable .get is a built in python dict method.
        code = (r.get("iataCode") or "").strip().upper() #<- the or "" make so even if its empty we
        # still search the rest of the list and return safe uppercase strings.
        if code and code != ORIGIN:
            dest_codes.append(code)

    #3) Common request params
    base_url = (flight_search._amadeus_api_base or "https://test.api.amadeus.com").rstrip("/")
    offers_url = f"{base_url}/v2/shopping/flight-offers"

    # You can make these inputs or config
    DEPARTURE = "2026-03-12"
    RETURN = "2026-03-21"  # comment this out for one-way
    ADULTS = "1"
    CURRENCY = "USD"
    MAX_OFFERS = "30"

    #4) Loop destinations → fetch offers → pick cheapest
    for dest in dest_codes:
        params = {
            "originLocationCode": ORIGIN,
            "destinationLocationCode": dest,
            "departureDate": DEPARTURE,
            # For one-way, remove the next line:
            "returnDate": RETURN,
            "adults": ADULTS,
            "currencyCode": CURRENCY,
            "max": MAX_OFFERS,
            # optional: "nonStop": "false"
        }

#Check if lowest price is cheaper than whats listed in the excel. If it's cheaper,
    # send out an email with that info. Enough to book flight, using notification manager
#The message should include:Price Departure Airport IATA Code,Arrival Airport,
        # IATA Code, Outbound Date,Inbound Date

        # [ADDED] begin per-destination event trace
        event = {
            "id": str(uuid.uuid4()),
            "origin": ORIGIN,
            "destination": dest,
            "request": {"url": offers_url, "params": params},
            "response": None,
            "cheapest": None,
            "error": None
        }

        try:
            # Use the shared GET helper (handles token refresh, retries, toggleable debug)
            resp = flight_search._get(offers_url, params)
            offers = []
            try:
                raw = resp.json() or {}
                offers = (raw.get("data") or [])
                # [ADDED] concise console log + response snapshot (first 3 offers)
                logger.info("%s->%s status=%s offers=%s", ORIGIN, dest, resp.status_code, len(offers))
                event["response"] = {
                    "status_code": resp.status_code,
                    "count": len(offers),
                    "sample": offers[:3],  # [ADDED] only first 3 to keep it readable
                }

                # ===========================
                # [ADDED] Collect all prices seen (grandTotal preferred, fallback to total)
                # ===========================
                prices = []
                currency_seen = None
                for o in offers:
                    p = (o.get("price") or {})
                    total_str = p.get("grandTotal") or p.get("total")
                    if total_str is None:
                        continue
                    try:
                        val = float(total_str)
                    except (TypeError, ValueError):
                        continue
                    prices.append(val)
                    if currency_seen is None:
                        currency_seen = p.get("currency")
                prices.sort()
                event["prices_seen"] = {"currency": currency_seen, "values": prices}
                if prices:
                    logger.info("%s->%s prices=%s %s", ORIGIN, dest, prices, currency_seen or "")
                else:
                    logger.info("%s->%s prices=(none)", ORIGIN, dest)
                # ===========================

            except Exception as je:
                logger.error("%s->%s JSON parse error: %s", ORIGIN, dest, je)
                event["response"] = {
                    "status_code": getattr(resp, "status_code", None),
                    "parse_error": str(je)
                }

            # Call the static method to pick the cheapest offer
            cheapest = FlightSearch._pick_cheapest(offers)

            # Find the matching sheet row for this destination
            row_for_dest = next(
                (r for r in sheet_data if (r.get("iataCode") or "").strip().upper() == dest),
                None
            )

            if row_for_dest:
                should_notify, payload = evaluate_price_drop(row_for_dest, cheapest)
                if should_notify:
                    notifier.send(
                        subject=payload["subject"],
                        body_text=payload["body_text"],
                        body_html=payload["body_html"],  # or None if you want plain-only
                        recipients=[MyEmailReciever],
                    )
                    logger.info("Notification sent for %s: %s", dest, payload["subject"])
                else:
                    logger.info("No price drop for %s (or missing baseline).", dest)
            else:
                logger.info("No matching sheet row for destination %s", dest)

            print(cheapest)
            if not cheapest:
                print(f"{ORIGIN}-> {dest}: (no offers)")
                logger.info("%s->%s no offers", ORIGIN, dest)  # [ADDED]
                event["cheapest"] = None
            else:
                total = (cheapest.get("price") or {}).get("total")
                currency = (cheapest.get("price") or {}).get("currency")
                print(f"{ORIGIN}-> {dest}: ${total}")
                logger.info("%s->%s cheapest=%s %s", ORIGIN, dest, total, currency)  # [ADDED]
                event["cheapest"] = {
                    "price_total": total,
                    "currency": currency
                }

        except requests.HTTPError as e:
            print(f"[HTTP {ORIGIN}-> {dest}] {e}")
            event["error"] = {
                "type": "HTTPError",
                "message": str(e),
                "status_code": getattr(getattr(e, "response", None), "status_code", None)
            }

        # [ADDED] append event to run trace
        run_trace["destinations"].append(event)

except Exception as ex:
    print("[Main cheapest search error]", ex)
# ==================================================

#Section for dealing with notication manager
# Using the class with stored state:
email_notifier = NotificationManager(
    sender=MyEmailSender,
    app_password=app_password,
    host="smtp.gmail.com",
    port=587,      # [KEPT] You set 587 here
    use_ssl=False,  # [KEPT] even though use_ssl=True+587 is unusual,
                   # the class now FALLS BACK to STARTTLS if SSL handshake fails.
    timeout=10
)

# HTML+plain example
email_notifier.send(
    subject="Test email 123 nick",
    body_text="TSLA crossed your threshold.",
   # body_html="<p><strong>TSLA</strong> crossed your threshold.</p>",  # [FIXED: unescaped HTML for email clients]
    recipients=[MyEmailReciever],
)

#
# # If you choose the @staticmethod version instead:
# NotificationManager.send_email_text2(
#     subject="Quick Text",
#     body="Plain text email.",
#     sender="you@gmail.com",
#     recipients=["them@example.com"],
#     app_password="app-password",
# )

# ===========================
# [ADDED] End-of-run summary (min/avg/max per destination)
# ===========================
summary = []
for ev in run_trace.get("destinations", []):
    prices = (ev.get("prices_seen") or {}).get("values") or []
    if not prices:
        summary.append({
            "destination": ev.get("destination"),
            "count": 0,
            "min": None,
            "avg": None,
            "max": None,
            "currency": (ev.get("prices_seen") or {}).get("currency")
        })
        continue
    mn = min(prices)
    mx = max(prices)
    avg = sum(prices) / len(prices)
    summary.append({
        "destination": ev.get("destination"),
        "count": len(prices),
        "min": round(mn, 2),
        "avg": round(avg, 2),
        "max": round(mx, 2),
        "currency": (ev.get("prices_seen") or {}).get("currency")
    })

logger.info("----- Price Summary (min/avg/max) -----")
for row in summary:
    dest = row["destination"]
    c = row["currency"] or ""
    if row["count"] == 0:
        logger.info("%s: (no prices)", dest)
    else:
        logger.info("%s: n=%s min=%s %s | avg=%s %s | max=%s %s",
                    dest, row["count"],
                    row["min"], c, row["avg"], c, row["max"], c)

run_trace["summary"] = summary

# [ADDED] finalize and write trace
run_trace["finished_utc"] = datetime.utcnow().isoformat() + "Z"
_write_trace_file(run_trace, "trace.json")
logger.info("Trace written to trace.json — open it in a JSON viewer")