print("Welcome to the tip calculator!")
bill = float(input("What was the total bill? $"))
tip = int(input("What percentage tip would you like to give? 10 12 15 "))
people = int(input("How many people to split the bill? "))
tip_decimal= (tip / 100)
tip_amount = int((tip_decimal * bill)/people)
per_person_amt = ((bill/people) + tip_amount)
final_amt= round(per_person_amt,2)
print(f"Each person should pay$ {final_amt}:")